version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/RIMA-Frontend/nodejs"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  labels:
  - "dependencies"
  - "javascript"
  - "RIMA-Frontend"

- package-ecosystem: "pip"
  directory: "/RIMA-Backend"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  labels:
  - "dependencies"
  - "javascript"
  - "RIMA-Backend"
