changelog:
  exclude:
    labels:
    - ignore-for-release

  categories:
    - title: 🎉 Exciting New Features
      labels:
      - enhancement

    - title: 🧰 Fixes
      labels:
      - bug

    - title: 🔗 Dependencies
      labels:
      - dependencies

    - title: 🎨 Other Changes
      labels:
      - '*'
      exclude:
        labels:
        - enhancement
        - bug
        - dependencies
