services:
  backend-api:
    platform: linux/x86_64
    build: .
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-rima-backend:${IMAGE_TAG:-latest}
    command: bin/api
    restart: always
    environment:
    - DJANGO_DEBUG="False"
    - DJANGO_LOGLEVEL=error
    - REDIS_HOST=backend-redis
    - POSTGRES_HOST=backend-db
    - TEMP_DIR=/home/app/.tmp
    - MODEL_DIR=/home/app/.model
    - MODEL_SERVER=http://model-server:8080/
    env_file:
    - ../configuration.env
    depends_on:
    - backend-db
    - backend-redis
    - model-server
    ports:
    - 8000:8080

  backend-worker:
    platform: linux/x86_64
    build: .
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-rima-backend:${IMAGE_TAG:-latest}
    command: bin/worker
    restart: always
    environment:
    - DJANGO_DEBUG="False"
    - DJANGO_LOGLEVEL=error
    - REDIS_HOST=backend-redis
    - POSTGRES_HOST=backend-db
    - TEMP_DIR=/home/app/.tmp
    - MODEL_DIR=/home/app/.model
    - MODEL_SERVER=http://model-server:8080/
    - PRELOAD_MODELS="true"
    env_file:
    - ../configuration.env
    depends_on:
    - backend-db
    - backend-redis
    - model-server

  backend-db:
    image: postgres:13.6
    restart: on-failure
    environment:
    - PRELOAD_MODELS="true"
    env_file:
    - ../configuration.env
    volumes:
    - database-data:/var/lib/postgresql/data/

  backend-redis:
    image: redis:6.2
    command: redis-server --loglevel warning --save "" --appendonly no
    restart: on-failure

volumes:
  database-data:
