# Generated by Django 2.2.3 on 2020-04-12 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0003_auto_20200411_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longterminterest', old_name='created_at', new_name='created_on'
        ),
        migrations.RenameField(
            model_name='longterminterest', old_name='updated_at', new_name='updated_on'
        ),
        migrations.RenameField(
            model_name='shortterminterest', old_name='created_at', new_name='created_on'
        ),
        migrations.RenameField(
            model_name='shortterminterest', old_name='updated_at', new_name='updated_on'
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('id_str', models.CharField(blank=True, max_length=2048, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('entities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('used_in_calc', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tweets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('paper_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('used_in_calc', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='papers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
