# Generated by Django 2.2.3 on 2020-04-15 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0005_auto_20200413_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                (
                    'categories',
                    models.ManyToManyField(
                        related_name='keywords', to='interests.Category'
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name='longterminterest', name='categories'),
        migrations.RemoveField(model_name='shortterminterest', name='categories'),
        migrations.AlterField(
            model_name='longterminterest',
            name='keyword',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='long_term_models',
                to='interests.Keyword',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortterminterest',
            name='keyword',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='short_term_models',
                to='interests.Keyword',
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlacklistedKeyword',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'keyword',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blacklisted_preference',
                        to='interests.Keyword',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blacklisted_keywords',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
