# Generated by Django 2.2.3 on 2020-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('interests', '0006_auto_20200415_1414')]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        )
    ]
