# Generated by Django 2.2.3 on 2020-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('interests', '0009_auto_20200418_1944')]

    operations = [
        migrations.AlterField(
            model_name='longterminterest',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='shortterminterest',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
