# Generated by Django 2.2.3 on 2020-04-22 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0010_auto_20200418_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTrend',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('weight', models.FloatField(default=1)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'keyword',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tends',
                        to='interests.Keyword',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trends',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
