# Generated by Django 2.2.3 on 2020-04-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('interests', '0011_interesttrend')]

    operations = [
        migrations.AddField(
            model_name='longterminterest',
            name='paper',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='paper_long_term_models',
                to='interests.Paper',
            ),
        ),
        migrations.AddField(
            model_name='longterminterest',
            name='tweet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tweet_long_term_models',
                to='interests.Tweet',
            ),
        ),
        migrations.AddField(
            model_name='shortterminterest',
            name='paper',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='paper_short_term_models',
                to='interests.Paper',
            ),
        ),
        migrations.AddField(
            model_name='shortterminterest',
            name='tweet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tweet_short_term_models',
                to='interests.Tweet',
            ),
        ),
    ]
