# Generated by Django 2.2.3 on 2020-04-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('interests', '0013_auto_20200428_2014')]

    operations = [
        migrations.RenameField(
            model_name='shortterminterest', old_name='paper', new_name='papers'
        ),
        migrations.RenameField(
            model_name='shortterminterest', old_name='tweet', new_name='tweets'
        ),
    ]
