# Generated by Django 2.2.3 on 2020-08-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0020_keyword_original_keyword_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='original_keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]