# Generated by Django 2.2.3 on 2020-10-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0021_keyword_original_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
