# Generated by Django 2.2.3 on 2022-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0022_auto_20201018_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='original_keywords_with_weights',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
