# Generated by Django 2.2.3 on 2023-04-02 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0023_keyword_original_keywords_with_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('papers_fetched', models.BooleanField(default=False)),
                ('interests_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsPaper',
            fields=[
                ('paper_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('authors', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True, default='', null=True)),
                ('used_in_calc', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(related_name='authors_paper', to='interests.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_AuthorsPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Keyword_AuthorsPapers_objects', to='interests.Keyword')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Keyword_AuthorsPapers', to='interests.AuthorsPaper')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('CITED_BY', 'CITED_BY'), ('REFERENCES', 'REFERENCES')], max_length=512)),
                ('value', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_citations', to='interests.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_citations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('Keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_keyword_interests', to='interests.Keyword')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_interests', to='interests.Author')),
                ('paper', models.ManyToManyField(related_name='authors_paper_objects', to='interests.AuthorsPaper')),
            ],
        ),
    ]
