# Generated by Django 2.2.3 on 2023-05-25 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0024_auto_20230430_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_blacklisted_paper',
            new_name='BlacklistedPaper',
        ),
        migrations.RenameModel(
            old_name='Keyword_Paper',
            new_name='KeywordPaper',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='author',
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_papers', to='interests.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='interests.Paper')),
            ],
        ),
    ]
