version: '3'

volumes:
  database-data:

services:
  frontend-web:
    build: RIMA-Frontend
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-rima-frontend:${IMAGE_TAG:-latest}
    restart: always
    environment:
    - BASE_URL=http://127.0.0.1:8000
    ports:
    - 8080:8080

  backend-api:
    build: RIMA-Backend
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-rima-backend:${IMAGE_TAG:-latest}
    command: bin/api
    restart: always
    environment:
    - DJANGO_DEBUG="False"
    - DJANGO_LOGLEVEL=error
    - REDIS_HOST=backend-redis
    - POSTGRES_HOST=backend-db
    - TEMP_DIR=/home/app/.tmp
    - MODEL_DIR=/home/app/.model
    - MODEL_SERVER=http://model-server:8080/
    env_file:
    - configuration.env
    depends_on:
    - backend-db
    - backend-redis
    - model-server
    ports:
    - 8000:8080

  backend-worker:
    build: RIMA-Backend
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-rima-backend:${IMAGE_TAG:-latest}
    command: bin/worker
    restart: always
    environment:
    - DJANGO_DEBUG="False"
    - DJANGO_LOGLEVEL=error
    - REDIS_HOST=backend-redis
    - POSTGRES_HOST=backend-db
    - TEMP_DIR=/home/app/.tmp
    - MODEL_DIR=/home/app/.model
    - MODEL_SERVER=http://model-server:8080/
    - PRELOAD_MODELS="true"
    env_file:
    - configuration.env
    depends_on:
    - backend-db
    - backend-redis
    - model-server

  backend-db:
    image: postgres:13.6
    restart: on-failure
    environment:
    - PRELOAD_MODELS="true"
    env_file:
    - configuration.env
    volumes:
    - database-data:/var/lib/postgresql/data/

  backend-redis:
    image: redis:6.2
    command: redis-server --loglevel warning --save "" --appendonly no
    restart: on-failure

  model-downloader:
    build: model-downloader
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-model-downloader:${IMAGE_TAG:-master}
    restart: on-failure
    environment:
    - MODEL_DIR=/home/app/.model
    - TEMP_DIR=/tmp
    env_file:
    - configuration.env
    volumes:
    - ./tmp/model:/home/app/.model

  model-server:
    build: model-server
    image: ${IMAGE_NAME_PREFIX:-ghcr.io/ude-soco/}rima-model-server:${IMAGE_TAG:-master}
    restart: on-failure
    volumes:
    - ./tmp/model:/usr/share/nginx/html
    depends_on:
    - model-downloader
