apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      initContainers:
      - name: downloader
        image: socialcomputing/rima-model-downloader
        env:
        - name: TEMP_DIR
          value: /tmp
        - name: MODEL_DIR
          value: /storage
        - name: GLOVE_MODEL_FILE
          value: glove/datatest_word2vec.txt
        envFrom:
        - secretRef:
            name: configuration
        volumeMounts:
        - name: storage
          mountPath: /storage
      - name: healthz
        image: busybox
        command: ['sh', '-c', 'touch /htdocs/healthz']
        volumeMounts:
        - name: storage
          mountPath: /htdocs
      containers:
      - name: server
        image: socialcomputing/rima-model-server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
