# Generated by Django 3.0.5 on 2020-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('accounts', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        )
    ]
