import React, {useEffect, useState} from "react";
import Chart from "chart.js";
import CloudChart from "../../ReuseableComponents/Charts/CloudChart/CloudChart";
import {useHistory} from "react-router-dom";

// core components
import {chartOptions, parseOptions} from "Services/variables/charts.js";
import swal from "@sweetalert/with-react";
import "../../../../assets/scss/custom.css";
import {Card, CardContent, Fade, Grid, IconButton, Paper, Switch, Tooltip, Typography} from "@material-ui/core";
import {Settings} from "@material-ui/icons";

export default function InterestOverview({classes}) {
  const history = useHistory();
  const [openDrawer, setOpenDrawer] = useState(true);

  useEffect(() => {
    if (window.Chart) {
      parseOptions(Chart, chartOptions());
    }
  }, []);


  const modalDetail = () => {
    swal(
      <div>
        <img
          style={{width: "70%", height: "40%"}}
          src={require("../../../../assets/img/Adv X IM.png")}
        />
      </div>
    );
  };
  return (
    <>
      <Card className={classes.cardHeight}>
        <CardContent>
          <Typography variant="h5" gutterBottom> Interest Overview </Typography>
          <Grid container justify="space-between" alignItems="center">
            <Grid item xs>
              <Typography>
                This chart shows your interests, which are extracted from your publications, tweets, or manually added
                keywords.
              </Typography>
            </Grid>
            <Grid item>
              <Grid container justify="flex-end" alignItems="center">
                <Grid item>
                  <Tooltip title={!openDrawer ?
                    <Typography> Show description </Typography> :
                    <Typography> Show only tag cloud </Typography>} arrow>
                    <Grid item>
                      <Switch color="primary" checked={openDrawer} onChange={() => setOpenDrawer(!openDrawer)}/>
                    </Grid>
                  </Tooltip>
                </Grid>
                <Grid item>
                  <Tooltip title={<Typography>Manage interests</Typography>} arrow>
                    <IconButton onClick={() => history.push("/app/Keyword")}>
                      <Settings color="primary"/>
                    </IconButton>
                  </Tooltip>
                </Grid>
              </Grid>
            </Grid>
          </Grid>

          <Grid container>

            <Grid item xs={12} lg={openDrawer ? 4 : ""} style={{display: openDrawer ? "block" : "none"}}>
              <Fade unmountOnExit in={openDrawer}>
                <Typography>
                  You can learn more about why/how your interest profile was generated by:
                  <br/><br/>
                  <li> Hovering over a keyword to see the <strong>source</strong> from where it was
                    extracted <i>(basic explanation)</i></li>
                  <li> Clicking on a keyword to see the <strong>related publications/tweets</strong> <i>(intermediate
                    explanation)</i></li>
                  <li> Clicking
                    <span onClick={modalDetail}
                          style={{marginLeft: "4px", marginRight: "4px", color: "blue", cursor: "pointer"}}>
                              <strong><u>here</u> </strong>
                            </span>
                    to see an example of the<strong> process</strong> leading to the generation of your interests <i>(advanced
                      explanation)</i> &nbsp;
                  </li>
                  <br/>
                  These basic, intermediate and advanced explanations refer to the amount of detail provided.
                  <br/><br/>
                </Typography>
              </Fade>
            </Grid>

            <Grid item xs={12} lg={openDrawer ? 8 : ""}>
              <CloudChart/>
            </Grid>
          </Grid>
        </CardContent>
      </Card>
    </>
  )
}
