apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: backend-

commonLabels:
  tier: backend

vars:
- name: DB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: db
- name: REDIS_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: redis

resources:
- api/deployment.yaml
- api/service.yaml
- worker/deployment.yaml
- db/deployment.yaml
- db/service.yaml
- db/pvc.yaml
- redis/deployment.yaml
- redis/service.yaml
