apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: model-

commonLabels:
  tier: model-server
  app.kubernetes.io/component: model-server

vars:
- name: MODEL_SERVER_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: server

resources:
- server/deployment.yaml
- server/service.yaml
- server/pvc.yaml
