# Generated by Django 2.2.3 on 2021-06-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_name_abbr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('conference_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference_Event',
            fields=[
                ('conference_event_name_abbr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('conference_event_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_event_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('conference_event_year', models.IntegerField(blank=True, null=True)),
                ('conference_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_events', to='conferences.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('platform_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference_Event_Paper',
            fields=[
                ('paper_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.IntegerField(null=True)),
                ('abstract', models.TextField(blank=True, default='', null=True)),
                ('no_of_cititations', models.IntegerField(blank=True, null=True)),
                ('citiations', models.CharField(max_length=1024, null=True)),
                ('paper_venu', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_event_papers', to='conferences.Conference_Event')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='platform_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='conferences.Platform'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('aliases', models.CharField(max_length=255, null=True)),
                ('influentialCitationCount', models.IntegerField(null=True)),
                ('author_name', models.CharField(max_length=255, null=True)),
                ('all_papers', models.CharField(max_length=1024, null=True)),
                ('author_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('papers_within_conference', models.ManyToManyField(to='conferences.Conference_Event_Paper')),
            ],
        ),
    ]
