# Generated by Django 2.2.3 on 2021-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('platform_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreloadedConferenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name_abbr', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
