# Generated by Django 2.2.3 on 2021-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference_event',
            name='id',
        ),
        migrations.AlterField(
            model_name='conference_event',
            name='conference_event_name_abbr',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
