# Generated by Django 2.2.3 on 2021-06-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20210622_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference_event',
            old_name='conference_event_year',
            new_name='no_of_stored_papers',
        ),
    ]
