# Generated by Django 2.2.3 on 2021-09-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference_Event',
            fields=[
                ('conference_event_name_abbr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('conference_event_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_event_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('no_of_stored_papers', models.IntegerField(blank=True, null=True)),
                ('conference_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_events', to='conferences.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_Event_Paper',
            fields=[
                ('paper_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.IntegerField(null=True)),
                ('abstract', models.TextField(blank=True, default='', null=True)),
                ('no_of_cititations', models.IntegerField(blank=True, null=True)),
                ('citiations', models.CharField(max_length=1024, null=True)),
                ('paper_venu', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_name_abbr', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_event_papers', to='conferences.Conference_Event')),
            ],
        ),
    ]
