# Generated by Django 2.2.3 on 2021-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20210624_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreloadedConferenceList',
            fields=[
                ('conference_name_abbr', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('conference_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
