# Generated by Django 2.2.3 on 2021-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conference_event_conference_event_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('semantic_scolar_author_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('aliases', models.CharField(max_length=255, null=True)),
                ('influentialCitationCount', models.IntegerField(null=True)),
                ('author_name', models.CharField(max_length=255, null=True)),
                ('all_papers', models.CharField(max_length=1024, null=True)),
                ('author_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author_has_Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Author')),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference_Event')),
                ('conference_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference_Event_Paper')),
            ],
            options={
                'unique_together': {('conference_event_name_abbr', 'author_id', 'paper_id')},
            },
        ),
        migrations.AddField(
            model_name='author',
            name='papers_within_conference',
            field=models.ManyToManyField(through='conferences.Author_has_Papers', to='conferences.Conference_Event_Paper'),
        ),
    ]
