# Generated by Django 2.2.3 on 2021-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_preloadedconferencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='preloadedconferencelist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preloadedconferencelist',
            name='conference_name_abbr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
