# Generated by Django 2.2.3 on 2021-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20210627_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_Event_keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keywrod', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
