# Generated by Django 2.2.3 on 2021-07-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_conf_event_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_has_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiegth', models.IntegerField(null=True)),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasEvents', to='conferences.Conference_Event')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haskeywords', to='conferences.Conf_Event_keyword')),
            ],
        ),
    ]
