# Generated by Django 2.2.3 on 2021-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_event_has_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_has_keyword',
        ),
    ]
