# Generated by Django 2.2.3 on 2021-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_conf_event_keyword_conference_event_name_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_Event_Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='conf_event_keyword',
            old_name='keywrod',
            new_name='keyword',
        ),
    ]
