# Generated by Django 2.2.3 on 2021-07-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_auto_20210703_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_has_keyword',
            old_name='wiegth',
            new_name='weigth',
        ),
        migrations.AlterField(
            model_name='event_has_keyword',
            name='conference_event_name_abbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords_Events', to='conferences.Conference_Event'),
        ),
        migrations.CreateModel(
            name='Event_has_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth', models.IntegerField(null=True)),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topics_Events', to='conferences.Conference_Event')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hastopics', to='conferences.Conf_Event_Topic')),
            ],
        ),
        migrations.AddField(
            model_name='conf_event_topic',
            name='conference_event_name_abbr',
            field=models.ManyToManyField(through='conferences.Event_has_Topic', to='conferences.Conference_Event'),
        ),
    ]
