# Generated by Django 2.2.3 on 2021-07-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20210703_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_has_keyword',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='event_has_topic',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.AlterUniqueTogether(
            name='event_has_keyword',
            unique_together={('conference_event_name_abbr', 'keyword_id')},
        ),
        migrations.AlterUniqueTogether(
            name='event_has_topic',
            unique_together={('conference_event_name_abbr', 'topic_id')},
        ),
    ]
