# Generated by Django 2.2.3 on 2021-07-24 11:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('conferences', '0013_auto_20210703_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='semantic_scolar_author_id',
        ),
    ]
