# Generated by Django 2.2.3 on 2021-07-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_auto_20210724_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_has_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_topics', to='conferences.Author')),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference_Event')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorhastopics', to='conferences.Conf_Event_Topic')),
            ],
            options={
                'unique_together': {('author_id', 'topic_id', 'conference_event_name_abbr')},
            },
        ),
        migrations.CreateModel(
            name='Author_has_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_keywords', to='conferences.Author')),
                ('conference_event_name_abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference_Event')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorhaskeywords', to='conferences.Conf_Event_Topic')),
            ],
            options={
                'unique_together': {('author_id', 'keyword_id', 'conference_event_name_abbr')},
            },
        ),
    ]
