# Generated by Django 2.2.3 on 2021-07-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0016_author_event_keyword_author_event_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_has_keyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorhaskeywords', to='conferences.Author_Event_keyword'),
        ),
        migrations.AlterField(
            model_name='author_has_topic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorhastopics', to='conferences.Author_Event_Topic'),
        ),
    ]
