# Generated by Django 2.2.3 on 2021-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20210724_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_event_keyword',
            name='author_id',
            field=models.ManyToManyField(through='conferences.Author_has_Keyword', to='conferences.Conference_Event'),
        ),
        migrations.AddField(
            model_name='author_event_topic',
            name='author_id',
            field=models.ManyToManyField(through='conferences.Author_has_Topic', to='conferences.Conference_Event'),
        ),
    ]
