# Generated by Django 2.2.3 on 2021-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0018_auto_20210724_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference_event_paper',
            name='conference_name_abbr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
