# Generated by Django 2.2.3 on 2021-07-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0019_conference_event_paper_conference_name_abbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='papers_within_conference',
        ),
    ]
