# Generated by Django 2.2.3 on 2021-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0021_author_has_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='papers_within_conference',
            field=models.ManyToManyField(through='conferences.Author_has_Papers', to='conferences.Conference_Event_Paper'),
        ),
    ]
