# Generated by Django 2.2.3 on 2021-07-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0022_author_papers_within_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_has_keyword',
            name='all_events',
            field=models.BooleanField(default=True),
        ),
    ]
