# Generated by Django 2.2.3 on 2021-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0023_author_has_keyword_all_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_has_keyword',
            name='all_events',
            field=models.BooleanField(default=False),
        ),
    ]
