# Generated by Django 2.2.3 on 2021-07-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0024_auto_20210727_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_has_keyword',
            name='conference_event_name_abbr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference_Event'),
        ),
    ]
