apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rima

resources:
- ../base

generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: web
  path: ingress.patch.yaml

secretGenerator:
- name: configuration
  env: configuration.env

images:
- name: ghcr.io/ude-soco/rima-model-downloader
  newTag: latest
- name: ghcr.io/ude-soco/rima-model-server
  newTag: latest
- name: ghcr.io/ude-soco/rima-rima-backend
  newTag: latest
- name: ghcr.io/ude-soco/rima-rima-frontend
  newTag: latest
- name: redis
  newTag: 6.2.13
- name: postgres
  newName: bitnami/postgresql
  newTag: 13.6.0
