apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/component: worker
    keel.sh/policy: patch
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: setup
        image: socialcomputing/rima-rima-backend
        command: ['bin/model/download']
        env:
        - name: MODEL_SERVER
          value: "http://$(MODEL_SERVER_SERVICE):8080"
        - name: MODEL_DIR
          value: /tmp/models
        volumeMounts:
        - mountPath: /tmp/models
          name: tmp
      containers:
      - name: worker
        image: socialcomputing/rima-rima-backend
        command: ['bin/worker']
        env:
        - name: POSTGRES_HOST
          value: $(DB_SERVICE)
        - name: REDIS_HOST
          value: $(REDIS_SERVICE)
        - name: TEMP_DIR
          value: /tmp
        - name: MODEL_DIR
          value: /tmp/models
        - name: MODEL_SERVER
          value: "http://$(MODEL_SERVER_SERVICE):8080"
        envFrom:
        - secretRef:
            name: configuration
        resources:
          requests:
            memory: 900Mi
            cpu: 50m
          limits:
            memory: 2Gi
            cpu: 500m
        startupProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - celery inspect ping -b redis://$REDIS_HOST
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 30 # (2 +) 15 minutes
        volumeMounts:
        - mountPath: /tmp/models
          name: tmp
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: worker
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: tmp
        emptyDir: {}
