apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/component: redis
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/component: redis
