---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app.kubernetes.io/component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
