apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/component: database
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/component: database
