# Generated by Django 2.2.3 on 2020-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('common', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='TriggerTask',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('task_type', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        )
    ]
