# Generated by Django 2.2.3 on 2020-04-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('common', '0002_triggertask')]

    operations = [
        migrations.AlterField(
            model_name='triggertask',
            name='task_type',
            field=models.CharField(
                choices=[
                    ('IMPORT_TWEETS', 'IMPORT_TWEETS'),
                    ('IMPORT_PAPERS', 'IMPORT_PAPERS'),
                    ('IMPORT_TWEETS_FOR_USER', 'IMPORT_TWEETS_FOR_USER'),
                    ('IMPORT_PAPERS_FOR_USER', 'IMPORT_PAPERS_FOR_USER'),
                    ('UPDATE_SHORT_TERM_MODEL', 'UPDATE_SHORT_TERM_MODEL'),
                    ('UPDATE_LONG_TERM_MODEL', 'UPDATE_LONG_TERM_MODEL'),
                    (
                        'UPDATE_SHORT_TERM_MODEL_FOR_USER',
                        'UPDATE_SHORT_TERM_MODEL_FOR_USER',
                    ),
                    (
                        'UPDATE_LONG_TERM_MODEL_FOR_USER',
                        'UPDATE_LONG_TERM_MODEL_FOR_USER',
                    ),
                ],
                max_length=255,
            ),
        )
    ]
