# Generated by Django 2.2.3 on 2020-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200512_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggertask',
            name='task_type',
            field=models.CharField(choices=[
                ('IMPORT_TWEETS', 'IMPORT_TWEETS'),
                ('IMPORT_PAPERS', 'IMPORT_PAPERS'),
                ('IMPORT_TWEETS_FOR_USER', 'IMPORT_TWEETS_FOR_USER'),
                ('IMPORT_PAPERS_FOR_USER', 'IMPORT_PAPERS_FOR_USER'),
                ('UPDATE_SHORT_TERM_MODEL', 'UPDATE_SHORT_TERM_MODEL'),
                ('UPDATE_LONG_TERM_MODEL', 'UPDATE_LONG_TERM_MODEL'),
                ('UPDATE_SHORT_TERM_MODEL_FOR_USER',
                 'UPDATE_SHORT_TERM_MODEL_FOR_USER'),
                ('UPDATE_LONG_TERM_MODEL_FOR_USER',
                 'UPDATE_LONG_TERM_MODEL_FOR_USER'),
                ('IMPORT_ALL_DATA', 'IMPORT_ALL_DATA'),
                ('IMPORT_PAPER_DATA', 'IMPORT_PAPER_DATA')
            ],
                                   max_length=255),
        ),
    ]
