name: CI

on:
  push:
    tags:       [ v*.*.* ]
    branches:   [ main ]
  pull_request:
    branches:   [ main ]

jobs:
  images:
    uses: ./.github/workflows/build.yml
    with:
      services:        "[ 'model-downloader', 'model-server', 'RIMA-Backend', 'RIMA-Frontend' ]"
      base_image_name: "socialcomputing/rima-"
      push:            ${{ github.event_name != 'pull_request' }}
    secrets:
      registry_user:   ${{ secrets.DOCKERHUB_USERNAME }}
      registry_token:  ${{ secrets.DOCKERHUB_TOKEN }}
