name: Continuous Integration

on:
  push:
    tags:       [ v*.*.* ]
    branches:   [ master, development ]
  pull_request:
    branches:   [ master ]

jobs:
  images:
    uses: ./.github/workflows/build.yml
    with:
      services:        "[ 'model-downloader', 'model-server', 'RIMA-Backend', 'RIMA-Frontend' ]"
      base_image_name: "socialcomputing/rima-"
      push:            ${{ github.event_name != 'pull_request' }}
    secrets:
      registry_user:   ${{ secrets.DOCKERHUB_USERNAME }}
      registry_token:  ${{ secrets.DOCKERHUB_TOKEN }}

  release:
    needs: [ images ]
    if:    github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses:  ./.github/workflows/release.yml
