name: Build Container Image

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push RIMA-Frontend
      uses: docker/build-push-action@v2
      with:
        file: ./RIMA-Frontend/Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/rima-frontend:latest
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rima-frontend:buildcache
        cache-to:   type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rima-frontend:buildcache,mode=max

    - name: Build and push RIMA-Backend
      uses: docker/build-push-action@v2
      with:
        file: ./RIMA-Backend/Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/rima-backend:latest
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rima-backend:buildcache
        cache-to:   type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rima-backend:buildcache,mode=max
