name: Release

on: workflow_call

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for stable semver
      id:   semver
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "stable=true" >> $GITHUB_OUTPUT
        fi

    - name: Create release
      if:   steps.semver.outputs.stable == 'true'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        allowUpdates: true
        updateOnlyUnreleased: true
        skipIfReleaseExists: true
        generateReleaseNotes: true
